### ISSUE TITLE
Add trait view `makeIfImbued` factory function

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO-TraitGen#18]
## What

Migrated from https://github.com/OpenAssetIO/OpenAssetIO/issues/816 since we're planning to get rid of `TraitBase`

`myTrait = MyTrait::ifImbued(traitsData)`, allowing for a workflow of `if myTrait := MyTrait.makeIfImbued(traitsData): ...` (Python) / `if (myTrait = MyTrait::makeIfImbued(traitsData)) { ...` (C++). This works since `shared_ptr` with a `nullptr` is falsey in C++ and `None` in Python.

**Comment by elliotcmorris** [comment]
Closing due to low priority/not sure it's the right pattern
