### ISSUE TITLE
Publish `openassetio-traitgen` to PyPI

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-TraitGen#2]
## What

Publish `openassetio-triatgen` to PyPI for Python 3.7, 3.9, 3.10

## Why

This will allow dependent projects such as https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation to automate its use as part of their build pipeline.

**Comment by feltech** [comment]
Closed in error - apparently `Closes #1` on my fork can close issues here?!

**Comment by foundrytom** [comment]
Capturing offline chat, make a temp API token from @feltech's Test PyPI account so the real releas won't fail. Use the other one for real PyPI.
