### ISSUE TITLE
[Core] Add trait `static` property accessors/mutators

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO-TraitGen#24]
## What

Add `static` variants of trait property accessors and mutators, e.g. `getMyPropertyFrom(traitsData)` / `setMyPropertyTo(traitsData)`

## Why

Currently trait view classes require construction around a `TraitsDataPtr` before property accessors/mutators can be used.  This involves a copy-construction of the `TraitsDataPtr`.  If the user only cares to query a particular property, then that copy-construction is a waste of resources.

Note that we already have `static` variants of `imbue`/`isImbued`, i.e. `imbueTo`/`isImbuedTo`, so doing similar for properties adds some functional parity.

**Comment by elliotcmorris** [comment]
Dupe of https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/issues/35
