### ISSUE TITLE
Validate traits in composed specifications at build time

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-TraitGen#66]
[plan] Good idea, but unfortunate that we can't trust that TraitGen did this validation already. Worth a TraitGen issue to look into?

_Originally posted by @feltech in https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/71#discussion_r1411816324_

## Acceptance Critera
- Validate in-library traits
- Only log warnings for out of library traits

**Comment by elliotcmorris** [comment]
This is about validating that the traits put in specifications are actually valid traits, this is non-trivial for cross-package specifications if we want to be strict about it ... which we might not want to be.

**Comment by feltech** [comment]
This is a duplicate of https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/issues/64
