### ISSUE TITLE
Validate required property

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO-TraitGen#79]
If we add a tag to the yaml schema `required` to each property, there is some validation we can do to be friendlier. Most directly, we can emit a better error message when the property is not set, so the recipient knows the error is not their fault, and knows who to go to to address it.

**Comment by feltech** [comment]
Carefully consider this in the context of established rules in our [GUIDELINES](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/blob/main/GUIDELINES.md)

**Comment by feltech** [comment]
I'm going to close this, since it reverses current guidelines, and the proposed solution wouldn't work anyway.
